### ISSUE TITLE
Нет бэкграунда у входящего сообщения в messager'е

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#14]

**Comment by sk1e** [comment]
Этот бэкграунд белый и его не видно. Зачем он нужен?

**Comment by sk1e** [comment]
мне кажется его просто удалить забыл тот кто рисовал этот макет

**Comment by sk1e** [comment]
может у @Znack  спросить зачем он там нужен

**Comment by in19farkt** [comment]
У сообщений бекграунд должен быть белым, а у месседжера серым.
![screenshot 2](https://cloud.githubusercontent.com/assets/12945918/21725106/908b5b8a-d469-11e6-9a48-8befc8c1bd6d.png)
Возможно у тебя моник не очень контрастный и бекграунд сообщения сливается с бекграундом мессенджера

**Comment by sk1e** [comment]
Похоже, у меня они оба белыми выглядят)
