### ISSUE TITLE
В percentage цифры не по центру

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#17]

**Comment by sk1e** [comment]
Они по центру просто сам центр так высчитывается. В стандарте есть пункт про ошибки дизайнеров, мне кажется он про это

**Comment by in19farkt** [comment]
Если смотреть по высоте шрифта, то по центру, если смотреть по высоте цифр, то уже не по центру.
Если выделить блок с цифрой, то видно что от верха цифры до верхнего края блока, расстояние немного меньше, чем аналогичное расстояние с противоположной стороны. Поэтому визуально и фактически получается, что цифра расположена не по центру)) И это не ошибка дизайнера)

**Comment by in19farkt** [comment]
И еще поправь цвет шрифта и толщину шкалы

**Comment by sk1e** [comment]
Я про это говорил — "Чаще всего не надо хардкодить какой-нибудь неочевидный отсуп, просто чтобы идеально соответсвовать макету - лучше сказать дизайнеру, что автоматом полоска ставится на другое место и её лучше там и оставить". 
В общем не важно, я исправил.

**Comment by in19farkt** [comment]
Да, во многих случаях так и есть, но не в этом. Согласись, цифра не по центру в круге сразу бросается в глаза. Тут единственное что можно сказать дизайнеру, так это то, чтобы он подобрал другой шрифт с цифрами в полную высоту шрифта, если такие вообще есть.

**Comment by sk1e** [comment]
Соглашусь) 
Там еще разные центры в разных процентажах в макете,  и в том числе по этому решил не заморачиваться тогда.
