### ISSUE TITLE
тултип слайдера

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#20]
Зачем в slider.pug в микшин tooltip передаются атрибуты tooltip и tooltipBody, если внутри микшина они не используются?
`+tooltip("dark-2", "bottom")(tooltip="slider__tooltip", tooltipBody="slider__tooltip-body")= 0`

**Comment by sk1e** [comment]
это у меня исправлено в https://github.com/sk1e/yasn/commit/891558377ea5359c7caba4aeeb1d5061ef6a8263
обновись плз, может еще что пофиксено там уже
