### ISSUE TITLE
Функции в классах элементов

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#27]
Функции attachCoordinates(), attachEventHandlers(), render() и т.д., правильнее будет вызывать внутри конструктора. Например, создание экземпляра кнопки не имеет смысла без привязки обработчиков, поэтому нужно делать эту привязку внутри конструктора.

**Comment by sk1e** [comment]
если их убрать в конструктор то eslint мне будет ошибку показывать

**Comment by in19farkt** [comment]
Что за ошибка?

**Comment by sk1e** [comment]
ошибка что созданный объект никак не используется

**Comment by in19farkt** [comment]
А ты его в переменную не записывай)

**Comment by sk1e** [comment]
Тогда будет ругаться что никуда не записываю созданный объект)

**Comment by in19farkt** [comment]
Один из немногоих случаев, когда экземпляр объекта в дальнейшем не используется, но сам подход с классами оправдан, поэтому тут два варианта, либо убрать переменную и ретёрнить создаваемый экземпляр, либо заигнорить это правило (на этой же строке допиши коммент `// eslint-disable-line no-new`), но глобально отключать это правило не стоит.

**Comment by sk1e** [comment]
Возвращать нельзя это уже будет костыль с искажением семантики . Правило лучше... но тогда его нужно будет приписывать к каждому созданию экземпляра. Экземпляры для этих классов у нас везде создаются в единичном количестве и вероятность количества экземпляров больше 1 очень низкая. Таким образом, с точки зрения повторного использования вариант с комментом будет хуже того что уже используется у меня: вызов методов просто переместится в конструктор и везде появится прибавка в виде коммента.

Еще нельзя исключать что могут появится очень странные желания, скажем, отрендерить, но не привязывать пока события и тогда методы вообще нельзя будет перемещать в конструктор . 

В общем я считаю все это очень спорным, относительным и зависимым от области будушего применения. Мне мой вариант, пока что, все-таки больше нравится и я не хочу его менять...

**Comment by in19farkt** [comment]
Тут есть несколько ньюансов, которые тоже надо учесть:
1. Все таки экземпляры мы создаем много раз, например, для той же кнопки, если ее три штуки на странице, то и экземпляров будет три.
2. Семантически тоже не совсем корректно кажется выносить навешивание событий и различные иниационные хуки за пределы конструктора, по логике это как раз при создании компоненты js должен сразу уметь делать, а так у нас API компоненты получается довольно странным - создай экземпляр, а потом еще вызови несколько методов, причем у разных компонент набор методов разный будет) еще интересно: мы, получается, делаем такое кривое API только потому что eslint ругается))
3. Странные желания лучше обрабатывать специальными опциями в конструкторе, и в идеале эти опции документировать хотя бы на уровне комментария
4. Есть вероятность, что вообще надо будет сделать экспорт всех инициализированных инстансов, тогда будет в конце каждой компоненты примерно такой код:
```
export default function renderComponent(callbackWhenInitialized) {
  $(() => {
    const buttons = $('.js-button').map((index, node) => {
      return new Button($(node));
    });

    if (callbackWhenInitialized && typeof callbackWhenInitialized === 'function') {
      callbackWhenInitialized(buttons);
    }
  });
}

renderComponent(); // вызываем сразу один раз, чтобы начальную страницу сынициализировать, в принципе потом и это можно будет убрать
```

**Comment by sk1e** [comment]
Пардон, экземпляров тут действительно обычно больше 1, это выражение, их создающее, одно.
Спасибо за развернутый ответ)
