### ISSUE TITLE
Снова кнопка

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#28]
Немного не доделал. Если у кнопки тень 3px, то при нажатии она должна опускаться на все 3px.

**Comment by in19farkt** [comment]
И в форме у кнопки сабмит поведение при нажатии осталось прежним

**Comment by sk1e** [comment]
Вообще я специально сделал так, там на пол тени она опускается. Если на всю тень, то она слишком дерганная какая-то становится

**Comment by in19farkt** [comment]
Используй transition чтобы не было дергано. А вообще, это же кнопка, она и должна быстро нажиматься и отжиматься)

**Comment by in19farkt** [comment]
А что с кнопками на форме, эвентах и месседжере?

**Comment by sk1e** [comment]
Им не понравивлся мой отступ) исправил
