### ISSUE TITLE
Тултип юзер профайла

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#30]
При переполнении текст выходит за границы, и хвост тултипа съезжает вверх.

**Comment by in19farkt** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/12945918/21725743/4ef0306c-d46c-11e6-90a9-d84f7f300ed6.png)

**Comment by sk1e** [comment]
Он же не предназначен для таких больших слов. 
По поводу хвоста — вообще, тут для реальных значений мне кажется должно хватить места и его вообще не надо удлинять в высоту. Если все же позволять удлиняться для каких-нибудь редких значений, то хвост не сместится намного и я бы забил на это вообще, т.к. через css, я так понял, не отцентрировать этот хвост и нужно будет в жс вычислять смещение.

**Comment by sk1e** [comment]
Исправил хвост

**Comment by in19farkt** [comment]
У меня изначально тултип съехал немного вверх (сравни с макетом), а при переполнении все по прежнему, хвост не по центру, тултип растягивается только вверх: 
![screenshot 7](https://cloud.githubusercontent.com/assets/12945918/21917738/a4f5888a-d97c-11e6-834d-5dfbfee445c9.png)
Это можно решить без JS, делай родительский контейнер флексом и релейтив, выравнивай дочерние элементы по центру, а тултип сделай абсолют и смещение от левого края на ширину аватарки. Должно получиться так:
![screenshot 8](https://cloud.githubusercontent.com/assets/12945918/21917898/15d3598c-d97e-11e6-803b-fd11d651e5c4.png)
Ну и переполнение очень длинными словами поправь.

**Comment by sk1e** [comment]
Исправил съезжающий тултип и переполнение длинными словами. 
Хвост у меня в центре, ты на каком браузере смотришь?

**Comment by sk1e** [comment]
Способ с флексом не работает в фф, там элемент с position: absolute неправильно понимает выравнивание контейнера. Я в самом начале так пробовал.

**Comment by in19farkt** [comment]
Я в хроме смотрел. Да, действительно, в фф такой способ не работает.

Еще один вариант без JS, к уже имеющимся стилям тултипа добавь:
```
bottom: 0;
transform: translateY(calc((100% - 7.8rem) / 2)); 
```
Здесь мы вычисляем половину разницы высот тултипа и аватарки, и сдвигаем тултип на получившуюся величину, тем самым центрируя его относительно аватарки. Вот результат:
![screenshot 9](https://cloud.githubusercontent.com/assets/12945918/21952485/ebc35f60-da50-11e6-85e9-d6ce064f0d46.png)

**Comment by sk1e** [comment]
Так у меня поломаются тултипы в комментах, где высота аватарки меньше.  Исправил для добавляемых комментов https://github.com/sk1e/yasn/commit/5842d7b7415fe13543f6ba23dc48eb8894497e2b
Может так его оставить?

**Comment by sk1e** [comment]
Оно нормально вообще сейчас выглядит у тебя?

**Comment by in19farkt** [comment]
Да, сейчас нормально всё.

Если у тебя не предусмотрено динамического изменения размеров аватарки, и она имеет всегда одинаковую известную нам высоту, то лучше будет решить это на уровне чистого css. Для блока с комментариями можно просто в стилях переопределить формулу с другим значением высоты аватарки.

**Comment by sk1e** [comment]
?
Сделал контейнер с фиксированной высотой, а в комментах уменьшил уже само изображение, т.к. все-таки оно большеватое там в полную высоту.
