### ISSUE TITLE
Переполнение news и events

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#32]
Тоже не очень красиво
![screenshot 5](https://cloud.githubusercontent.com/assets/12945918/21725903/e980c772-d46c-11e6-9462-b147688cce10.png)
Думаю будет правильно как-то ограничить высоту

**Comment by sk1e** [comment]
?

**Comment by in19farkt** [comment]
Ну тоже вариант) Я им задавал фиксированную высоту, т.к. предполагал что это карточки, которые будут располагаться в сетке, и переполнение одной из карточек приведет к не красивым последствиям.
