### ISSUE TITLE
Пропустил в двух местах префикс js-. По issue #21

### ISSUE THREAD

**Issue by in19farkt** [sk1e/yasn#35]
а именно: [20-ая строка](https://github.com/sk1e/yasn/blob/f434516f134b2b38f33031f2cedd7fa9fe711003/web_modules/blocks/search/index.js#L20) и [66-ая строка](https://github.com/sk1e/yasn/blob/f434516f134b2b38f33031f2cedd7fa9fe711003/web_modules/blocks/sign-up/index.js#L66)

**Comment by sk1e** [comment]
спасибо за точность)
